DROP TABLE IF EXISTS permissao CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;
DROP TABLE IF EXISTS post CASCADE;
DROP TABLE IF EXISTS amizade CASCADE;
DROP TABLE IF EXISTS curtida CASCADE;
DROP TABLE IF EXISTS comentario CASCADE;

CREATE TABLE usuario (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	nome VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	data_nascimento DATE NOT NULL,
	apelido VARCHAR(50),
	senha VARCHAR(128) NOT NULL,
	imagem_perfil VARCHAR(512),
	ativo BOOLEAN NOT NULL
);
ALTER TABLE usuario ADD CONSTRAINT pk_usuario PRIMARY KEY (id);
ALTER TABLE usuario ADD CONSTRAINT uk_usuario_email UNIQUE (email);

CREATE TABLE amizade (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	usuario_id BIGINT NOT NULL,
	amigo_id BIGINT NOT NULL,
	situacao VARCHAR(12)
);
ALTER TABLE amizade ADD CONSTRAINT pk_amizade PRIMARY KEY (id);
ALTER TABLE amizade ADD CONSTRAINT uk_amizade UNIQUE (id);
ALTER TABLE amizade ADD CONSTRAINT fk_amizade FOREIGN KEY (usuario_id) REFERENCES usuario;
ALTER TABLE amizade ADD CONSTRAINT fk_amizade_amigo FOREIGN KEY (amigo_id) REFERENCES usuario;

CREATE TABLE permissao (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	funcao VARCHAR(100) NOT NULL,
	usuario_id BIGINT NOT NULL
);
ALTER TABLE permissao ADD CONSTRAINT pk_permissao PRIMARY KEY (id);
ALTER TABLE permissao ADD CONSTRAINT uk_permissao UNIQUE (funcao, usuario_id);
ALTER TABLE permissao ADD CONSTRAINT fk_permissao_usuario FOREIGN KEY (usuario_id) REFERENCES usuario;

CREATE TABLE post (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,	
	titulo VARCHAR(100) NOT NULL,
	imagem VARCHAR(512) NOT NULL,
	texto VARCHAR(255),
	data_inclusao DATE NOT NULL,
	publico BOOL NOT NULL,
	usuario_id BIGINT
);
ALTER TABLE post ADD CONSTRAINT pk_post PRIMARY KEY (id);
ALTER TABLE post ADD CONSTRAINT uk_post UNIQUE (id);
ALTER TABLE post ADD CONSTRAINT fk_post_usuario FOREIGN KEY (usuario_id) REFERENCES usuario;

CREATE TABLE curtida (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	post_id BIGINT NOT NULL,
	usuario_id BIGINT NOT NULL,
	has_like BOOL
);
ALTER TABLE curtida ADD CONSTRAINT pk_curtida PRIMARY KEY(id);
ALTER TABLE curtida ADD CONSTRAINT uk_curtida UNIQUE(usuario_id, post_id);
ALTER TABLE curtida ADD CONSTRAINT fk_curtida_usuario FOREIGN KEY (usuario_id) REFERENCES usuario ON DELETE CASCADE;
ALTER TABLE curtida ADD CONSTRAINT fk_curtida_post FOREIGN KEY (post_id) REFERENCES post ON DELETE CASCADE;

CREATE TABLE comentario (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	post_id BIGINT NOT NULL,
	usuario_id BIGINT NOT NULL,
	comentario_texto VARCHAR(255),
	comentario_imagem VARCHAR(255)
);
ALTER TABLE comentario ADD CONSTRAINT pk_comentario PRIMARY KEY(id);



insert into usuario (nome, email, data_nascimento, apelido, senha, imagem_perfil, ativo) values ('Risonho','teste@cwi.com.br', '1999-03-22','', '$2a$10$4nYwyrDm0D2oFNSkf8MKtuhl.1qf4mWQgCtCT24zM4txtYBQklQfa','https://media.tenor.com/oa1Wk6YPHmgAAAAC/pepe-laugh-he-doesnt-know.gif',true);
insert into usuario (nome, email, data_nascimento, apelido, senha, imagem_perfil, ativo) values ('Luigi','teste123@cwi.com.br', '1999-03-22','', '$2a$10$Kl0g3ZrlQqWBbVVLoiTFc.AiSxOVNm9fwSFU2S3sA7EKXH4wl7Qyu','https://i.imgur.com/pMwDZn6.png',true);
insert into usuario (nome, email, data_nascimento, apelido, senha, imagem_perfil, ativo) values ('Testador de amizades','teste1234@cwi.com.br', '1999-03-22','HA HA HA', '$2a$10$6rM.A49J5IG3VzUizKyBCeT5Wbb07KE9xffasCrcvTBh5S6Y3B9G6','https://api.time.com/wp-content/uploads/2016/10/pepe-the-frog-matt-furie-hate-symbol-racism-anti-defamation-league-4chan.jpg',true);
insert into usuario (nome, email, data_nascimento, apelido, senha, imagem_perfil, ativo) values ('Pepe','teste2@cwi.com.br', '1999-03-22','Pepe', '$2a$10$JebbiMw4AmXjLoYhOKxfhOKfE/.Rbl985kX570.6VOvHht54E2XPC','https://media.tenor.com/JQEJtU1Mi0AAAAAd/pepetired-kiwimeli.gif',true);
insert into usuario (nome, email, data_nascimento, apelido, senha, imagem_perfil, ativo) values ('Mario','teste3@cwi.com.br', '1999-03-22','', '$2a$10$y4NJH3ajCyu1p8vspDM0qekt5elt6phet8jK7WhvZtATwUOTXKN6W','https://media.tenor.com/oa1Wk6YPHmgAAAAC/pepe-laugh-he-doesnt-know.gif',true);

insert into permissao (funcao, usuario_id) values ('ADMIN', 1);
insert into permissao (funcao, usuario_id) values ('USUARIO', 1);
insert into permissao (funcao, usuario_id) values ('USUARIO', 2);
insert into permissao (funcao, usuario_id) values ('USUARIO', 3);
insert into permissao (funcao, usuario_id) values ('USUARIO', 4);
insert into permissao (funcao, usuario_id) values ('USUARIO', 5);

INSERT INTO post (titulo, imagem, texto, data_inclusao, publico, usuario_id) values ('super POST', 'https://media.tenor.com/rsyenE0Ra_wAAAAi/pepe-herve.gif','','2023-02-26',true,1);
INSERT INTO post (titulo, imagem, texto, data_inclusao, publico, usuario_id) values ('super POST 2', 'https://media.tenor.com/rsyenE0Ra_wAAAAi/pepe-herve.gif','texto descritivo','2023-02-26',true,5);
INSERT INTO post (titulo, imagem, texto, data_inclusao, publico, usuario_id) values ('post cansado', 'https://media.tenor.com/rsyenE0Ra_wAAAAi/pepe-herve.gif','cansado','2023-02-26',true,3);
INSERT INTO post (titulo, imagem, texto, data_inclusao, publico, usuario_id) values ('filler post', 'https://media.tenor.com/rsyenE0Ra_wAAAAi/pepe-herve.gif','filler','2023-02-26',true,2);
INSERT INTO post (titulo, imagem, texto, data_inclusao, publico, usuario_id) values ('Cheguei amigos olhem meu chapeu', 'https://media.tenor.com/OBV6cg3yBO4AAAAj/mlady.gif','Sim o chapeu eh meu','2023-02-26',true,1);
INSERT INTO post (titulo, imagem, texto, data_inclusao, publico, usuario_id) values ('To zerado guris', 'https://media.tenor.com/rsyenE0Ra_wAAAAi/pepe-herve.gif','','2023-02-26',true,5);

INSERT INTO comentario (post_id, usuario_id, comentario_texto, comentario_imagem) VALUES (1,1,'belo post','');
INSERT INTO comentario (post_id, usuario_id, comentario_texto, comentario_imagem) VALUES (1,1,'belo post','');
INSERT INTO comentario (post_id, usuario_id, comentario_texto, comentario_imagem) VALUES (1,1,'belo post','');
INSERT INTO comentario (post_id, usuario_id, comentario_texto, comentario_imagem) VALUES (3,1,'belo post','');
INSERT INTO comentario (post_id, usuario_id, comentario_texto, comentario_imagem) VALUES (3,1,'belo post','');
INSERT INTO comentario (post_id, usuario_id, comentario_texto, comentario_imagem) VALUES (3,1,'belo post','');
INSERT INTO comentario (post_id, usuario_id, comentario_texto, comentario_imagem) VALUES (4,1,'belo post','');
INSERT INTO comentario (post_id, usuario_id, comentario_texto, comentario_imagem) VALUES (5,1,'belo post','');
INSERT INTO comentario (post_id, usuario_id, comentario_texto, comentario_imagem) VALUES (6,1,'belo post','https://media.tenor.com/IaSQ2CvyEAoAAAAi/pepepoint-pepe.gif');
INSERT INTO comentario (post_id, usuario_id, comentario_texto, comentario_imagem) VALUES (5,7,'gostei, tenho um italiano','https://external-preview.redd.it/o04ivm-MbbSPZffHhHXfJNf9cl9WUcUUrILONrugm0I.png?auto=webp&v=enabled&s=026eab0221f4b2ed9465e3fb8b9571bfc36af866');
INSERT INTO comentario (post_id, usuario_id, comentario_texto, comentario_imagem) VALUES (5,1,'belo post','');
INSERT INTO comentario (post_id, usuario_id, comentario_texto, comentario_imagem) VALUES (6,1,'belo post','');
INSERT INTO comentario (post_id, usuario_id, comentario_texto, comentario_imagem) VALUES (4,1,'belo post','');



INSERT INTO amizade (usuario_id, amigo_id, situacao) VALUES (1,2,'ACEITA');
INSERT INTO amizade (usuario_id, amigo_id, situacao) VALUES (3,1,'ACEITA');
INSERT INTO amizade (usuario_id, amigo_id, situacao) VALUES (4,1,'PENDENTE');
INSERT INTO amizade (usuario_id, amigo_id, situacao) VALUES (5,1,'PENDENTE');
insert into usuario (nome, email, data_nascimento, apelido, senha, imagem_perfil, ativo) values ('Mario','teste43@cwi.com.br', '1999-03-22','', '$2a$10$y4NJH3ajCyu1p8vspDM0qekt5elt6phet8jK7WhvZtATwUOTXKN6W','https://media.tenor.com/oa1Wk6YPHmgAAAAC/pepe-laugh-he-doesnt-know.gif',true);
insert into usuario (nome, email, data_nascimento, apelido, senha, imagem_perfil, ativo) values ('Mario','teste32@cwi.com.br', '1999-03-22','', '$2a$10$y4NJH3ajCyu1p8vspDM0qekt5elt6phet8jK7WhvZtATwUOTXKN6W','https://media.tenor.com/oa1Wk6YPHmgAAAAC/pepe-laugh-he-doesnt-know.gif',true);



