version: "3"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=bePepe
      - POSTGRES_PASSWORD=bePepe
      - POSTGRES_DB=bePepe
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./data/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - app
    ports:
      - "5432:5432"
    restart: always

  app:
    depends_on:
      - postgres
    container_name: bepepe
    build:
      context: .
      dockerfile: Dockerfile
    image: bepepe:v1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/bePepe
      - SPRING_DATASOURCE_USER=bePepe
      - SPRING_DATASOURCE_PASSWORD=bePepe
    ports:
      - "8080:8080"
    networks:
      - app

volumes:
  postgres-data:

networks:
  app: